### ISSUE TITLE
Contribution Report - Community Contribution Details (Jency Stella)

### ISSUE THREAD

**Issue by jency26** [postman-open-technologies/Postman-Supernova-Program#10]
# Contribution Report

## Contribution Type
- [x] Event Speaking

### For event types, was this event in-person, virtual or hybrid?
- [x] Virtual

### Contribution Name
1. AXIOM SUMMIT 2022 - Demystifying API Testing
2. UNICOM Conference - API Testing with POSTMAN
3. Synapse SuperVoice 2022 - Let's Flow with Flows
4. Test Tribe Dec 2022 - Virtual Meetup - API Testing Got Real
5. TestFlix 2022 - API Testing Unlocked
6. Automation Guild 2023 - Codeless Testing with Postman
7. Women in Tech Global Conference 2023 - Codeless Testing with Postman

### Contribution Date
These are past events already accomplished

### Link to Contribution
1. AXIOM SUMMIT 2022 - Delivered my first talk on the title "Demystifying API Testing" (Abstract link: https://www.youtube.com/watch?v=VmApZNWXaNU)
2. UNICOM Conference - API Testing with POSTMAN (Abstract link: https://www.youtube.com/watch?v=f44Wh-XcKV4)
3. Synapse SuperVoice 2022 - Let's Flow with Flows (Presentation Link: https://www.youtube.com/watch?v=NJPkbb0xseQ - starts at 03:00)
4. Test Tribe Dec 2022 - Virtual Meetup - API Testing Got Real (Presentation Link: https://www.youtube.com/watch?v=RbJIkvsMwok)
5. TestFlix 2022 - API Testing Unlocked (Presentation Link: https://www.youtube.com/watch?v=8LZieuvfgV8)
6. Automation Guild 2023 - Codeless Testing with Postman (Teaser Link: https://www.youtube.com/watch?v=AfoluXEJGnw)
7. Women in Tech Global Conference 2023 - Codeless Testing with Postman (Poster Link: https://www.linkedin.com/feed/update/urn:li:activity:7061664024987402240/)

### How many people attended your event/talk/livestream or video?
Roughly 50 to 80

# Social Media Links
Same as the ones shared under ### Link to Contribution

# Additional Comments?
Nothing here

**Comment by Kcorb95** [comment]
Thanks @jency26!

all of this looks really great! As part of the Supernova program, we require members to contribute on a quarterly basis. If you can put together a contribution for this quarter, I can get you added to the program :)

Once you have completed this initial contribution, we will be able to officially and formally invite you into the program and announce your achievements on our channels!

Let me know if you have any questions or if there's anything I can do to help.

**Comment by jency26** [comment]
Sure noted on this
