### ISSUE TITLE
Contribution Proposal - API Security Test With POSTMAN (Jency Stella)

### ISSUE THREAD

**Issue by jency26** [postman-open-technologies/Postman-Supernova-Program#11]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking

### For event types, will this event be in-person, virtual or hybrid?
- [ ] In-Person

### Contribution Name
API Security Test With POSTMAN

### Contribution Date
10/19/2023

### Link to Contribution (optional)
https://embedded.qatest.org/jency-stella/?lang=en&utm_source=Linkedin&utm_medium=Tarjeton&utm_campaign=Jency+Stella
https://www.linkedin.com/posts/qa-test-embedded-conference_qatest-embedded-2023-speaker-jency-stella-activity-7075026308673458177-Kd0O?utm_source=share&utm_medium=member_desktop

### Projected Attendance (optional)
Roughly 200 Attendees

# Details
QA&TEST Embedded 2023 - 22nd International Conference on Embedded Software Testing
Happening On - 18,19,20 October 2023
Happening At - Euskalduna Palace – Bilbao

**Comment by Kcorb95** [comment]
Thanks @jency26!

all of this looks really great! As part of the Supernova program, we require members to contribute on a quarterly basis. If you can put together a contribution for this quarter, I can get you added to the program :)

Once you have completed this initial contribution, we will be able to officially and formally invite you into the program and announce your achievements on our channels!

Let me know if you have any questions or if there's anything I can do to help.

**Comment by Kcorb95** [comment]
Thanks @jency26 ! Please also share on social media and the community forums as we get closer to the event :)

**Comment by jency26** [comment]
Hi @Kcorb95  the event is completed.
