### ISSUE TITLE
Contribution Proposal - Elucidation Of API Testing (Jency Stella)

### ISSUE THREAD

**Issue by jency26** [postman-open-technologies/Postman-Supernova-Program#12]
# Contribution Proposal

## Contribution Type
- [x] Event Speaking

### For event types, will this event be in-person, virtual or hybrid?
- [x] Virtual

### Contribution Name
Elucidation Of API Testing

### Contribution Date
08/29/2023

### Link to Contribution (optional)
(https://events.teams.microsoft.com/event/a14ffa9f-5721-40ee-8b88-e0c3f03ece01@3255b33a-073d-47e4-a4fe-6ab59a3e668e)](https://events.teams.microsoft.com/event/a14ffa9f-5721-40ee-8b88-e0c3f03ece01@3255b33a-073d-47e4-a4fe-6ab59a3e668e)

### Projected Attendance (optional)
Roughly 50 Attendees

# Details

𝐈𝐧𝐭𝐫𝐨𝐝𝐮𝐜𝐭𝐢𝐨𝐧 𝐓𝐨 𝐏𝐨𝐬𝐭𝐦𝐚𝐧:

Join me at the [BugRaptors - Software Testing Company](https://www.linkedin.com/company/bug-raptors/) upcoming webinar, “Introduction To Postman” highlighting the significance of APIs and details of API testing.

From improved communication between different digital platforms to effective automation and secure integration, API testing is vital to verify the functionalities of the product under test. This session will highlight the various aspects of API Testing using Postman such as sending requests, managing collections, defining test environments, etc. with interesting examples live.

𝐖𝐡𝐞𝐧 𝐢𝐬 𝐢𝐭 𝐡𝐚𝐩𝐩𝐞𝐧𝐢𝐧𝐠:
 𝐀𝐮𝐠𝐮𝐬𝐭 29, 2023 at 6:30 𝐏𝐌 - 7:30 𝐏𝐌 (𝐌𝐘𝐓) / 12:30 𝐏𝐌 – 1:30 𝐏𝐌 (𝐂𝐄𝐒𝐓) / 4:00 𝐏𝐌 - 5:00𝐏𝐌 (𝐈𝐒𝐓)
 - 𝐎𝐧𝐥𝐢𝐧𝐞

𝐄𝐯𝐞𝐧𝐭 𝐋𝐢𝐧𝐤: [Microsoft Virtual Events Powered by Teams](https://events.teams.microsoft.com/event/a14ffa9f-5721-40ee-8b88-e0c3f03ece01@3255b33a-073d-47e4-a4fe-6ab59a3e668e)

𝐑𝐞𝐠𝐢𝐬𝐭𝐞𝐫 𝐋𝐢𝐧𝐤 - [Microsoft Virtual Events Powered by Teams](https://events.teams.microsoft.com/event/a14ffa9f-5721-40ee-8b88-e0c3f03ece01@3255b33a-073d-47e4-a4fe-6ab59a3e668e/registration)

𝐀𝐛𝐨𝐮𝐭 𝐦𝐞:
 Myself 𝐉𝐞𝐧𝐜𝐲 𝐒𝐭𝐞𝐥𝐥𝐚 a ‘𝑻𝒆𝒔𝒕 𝑬𝒏𝒈𝒊𝒏𝒆𝒆𝒓’ by profession. I have been investigating the line between Software and Testing for the past 9+𝒚𝒆𝒂𝒓𝒔. My love affair with ‘𝘚𝘰𝘧𝘵𝘸𝘢𝘳𝘦 𝘛𝘦𝘴𝘵𝘪𝘯𝘨’ began years ago, currently working as ‘𝐋𝐞𝐚𝐝 𝐐𝐀 𝐄𝐧𝐠𝐢𝐧𝐞𝐞𝐫’ on the role of a passionate ‘𝑨𝑷𝑰 𝑻𝒆𝒔𝒕𝒆𝒓’ at a fast-growing Tech company “𝐁𝐢𝐥𝐥𝐞𝐧𝐧𝐢𝐮𝐦 𝐈𝐓 𝐒𝐞𝐫𝐯𝐢𝐜𝐞𝐬 (𝐌) 𝐒𝐝𝐧. 𝐁𝐡𝐝”. I love to spend my time investigating the APIs and exploring the concepts and interesting facts in and around Software Testing.

Other interesting facts about me - 𝐌𝐎𝐌 𝐨𝐟 𝐚 5𝐲𝐞𝐚𝐫 𝐨𝐥𝐝 𝐒𝐮𝐩𝐞𝐫𝐡𝐞𝐫𝐨 | 𝐈𝐒𝐓𝐐𝐁 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐞𝐝 - 𝐂𝐓𝐀𝐋-𝐓𝐌, 𝐂𝐓𝐀𝐄, 𝐂𝐓𝐅𝐋 | 𝐂𝐞𝐫𝐭𝐢𝐟𝐢𝐞𝐝 𝐌𝐞𝐧𝐭𝐨𝐫 | 𝐁𝐥𝐨𝐠𝐠𝐞𝐫 | 𝐂𝐨𝐦𝐦𝐮𝐧𝐢𝐭𝐲 𝐂𝐨𝐧𝐭𝐫𝐢𝐛𝐮𝐭𝐨𝐫 | 𝐎𝐜𝐚𝐬𝐬𝐢𝐨𝐧𝐚𝐥 𝐘𝐨𝐮𝐭𝐮𝐛𝐞𝐫 (𝐄𝐧𝐭𝐞𝐫𝐭𝐚𝐢𝐧𝐦𝐞𝐧𝐭).

**Comment by Kcorb95** [comment]
Looking forward to hearing more @jency26 ! 

Please also be sure to share on social media and the [Postman community forums](https://community.postman.com/c/events/6) when you have a talk title and abstract.
We'll use that info to share on our own channels to help promote your participation :)

**Comment by jency26** [comment]
hi @Kcorb95 noted on that, so in that case my upcoming webinar is planned for August 29th once done should I update you? Or should I directly comment here and you will take it up from there?

Kindly revert with your commmets.

**Comment by Kcorb95** [comment]
After the event, you can fill out a [contribution report](https://airtable.com/appgTEMsLIUf1NXUj/shrM6Uh7WqOEJJQZ7) and I'll be notified of it's completion :)

**Comment by jency26** [comment]
Hi @Kcorb95 the event is finalized and I added the details in the issue above. Also the same is posted in the community forum - https://community.postman.com/t/webinar-alert-introduction-to-postman-highlighting-the-significance-of-apis-and-details-of-api-testing/50879?u=jency.stella19

**Comment by jency26** [comment]
Hi @Kcorb95 the event is done today and the contribution proposal is submitted too. Kindly help to review the same.

**Comment by Kcorb95** [comment]
Thanks Jency and congrats!
