### ISSUE TITLE
Contribution Proposal - Talk at TestFlix about Generative AI in API testing (Valentin Despa)

### ISSUE THREAD

**Issue by vdespa** [postman-open-technologies/Postman-Supernova-Program#13]
# Contribution Proposal

## Contribution Type
- [X] Event Speaking
- [ ] Event Hosting
- [ ] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [X] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Generative AI in API testing with Postman (pending title)

### Contribution Date
09/23/2023

### Link to Contribution (optional)
Link to your contribution, if applicable

### Projected Attendance (optional)
Rough estimates are acceptable

# Details
What are your plans for this contribution?

Create a short talk about generative AI tests within Postman.

**Comment by Kcorb95** [comment]
Thanks @vdespa ! This is a really hot topic right now, looking forward to watching your talk :)

When you have an idea for your talk abstract, please do share on the [community forums](https://community.postman.com/c/events/6) and let me know so we can schedule some marketing to promote.
