### ISSUE TITLE
Contribution Proposal - Creating APIs with Flask and testing in Postman (Teri Eyenike)

### ISSUE THREAD

**Issue by Terieyenike** [postman-open-technologies/Postman-Supernova-Program#14]
# Contribution Proposal

## Contribution Type
- [ ] Article / Blog Post

### Contribution Name
Creating APIs with Flask and testing in Postman

### Contribution Date
N/A

### Link to Contribution (optional)
N/A

# Details
Publish the article on Dev.to and cross-post to other platforms. I will ensure the use of the right keywords for visibility.

**Comment by Kcorb95** [comment]
Great idea @Terieyenike ! Let me know when it's been posted and I'll schedule some stuff on our end as well :)

Also, when you have some time, please do share in the [community forums](https://community.postman.com/c/content-showcase/7) as well.

**Comment by Terieyenike** [comment]
Sharing to the community forums, is it before or after publishing your work @Kcorb95?

**Comment by Terieyenike** [comment]
Perfect. I will do that as I was awaiting your response.
Thank you.

**Comment by Kcorb95** [comment]
Also, please fill out a [contribution report](https://airtable.com/appgTEMsLIUf1NXUj/shrM6Uh7WqOEJJQZ7) so that we can begin onboarding you officially as a Supernova!

**Comment by Terieyenike** [comment]
@Kcorb95 I will submit it officially tomorrow and fill out the contribution report form.

**Comment by Terieyenike** [comment]
Hi @Kcorb95,
I have published my work.
