### ISSUE TITLE
Contribution Proposal -  Postman: VS Code Extension (Temitope Agbaje)

### ISSUE THREAD

**Issue by TemitopeAgbaje** [postman-open-technologies/Postman-Supernova-Program#15]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking
- [ ] Event Hosting
- [X] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [ ] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Postman: VS Code Extension

### Contribution Date
08/02/2023

### Link to Contribution (optional)
[Postman: VS Code Extension](https://dev.to/temitopeagbaje/postman-vscode-extension-3ljc)

# Details
This inform people on the Postman Extension and how they can go about using it

**Comment by Kcorb95** [comment]
Thanks @TemitopeAgbaje !

If you can share this on the [community forums](https://community.postman.com/c/content-showcase/7) and also fill out a [contribution report](https://airtable.com/appgTEMsLIUf1NXUj/shrM6Uh7WqOEJJQZ7), I'd love to get you officially onboarded as a Supernova!

**Comment by TemitopeAgbaje** [comment]
Thanks @Kcorb95 , I have done these
