### ISSUE TITLE
Contribution Proposal - Equity Scholars Techhub (Edwin Kuria)

### ISSUE THREAD

**Issue by edwinwkuria** [postman-open-technologies/Postman-Supernova-Program#17]
# Contribution Proposal

## Contribution Type
- [X] Event Speaking

### For event types, will this event be in-person, virtual or hybrid?
- [X] In-Person

### Contribution Name
Introduction to Automated API testing on postman.

### Contribution Date
08/27/2023

### Link to Contribution (optional)
Not Published yet.

### Projected Attendance (optional)
20 - 30

# Details
Equity Scholars Techhub will be hosting a session on building API's. 
I will build on the session by showing how we can write and run tests on the API's. Both manually and with automated runs on postman. 

The sessions will be hosted at Equity Center, Upper Hill, Nairobi Kenya.

**Comment by Kcorb95** [comment]
Thanks @edwinwkuria!

Please also be sure to share on social media and the [Postman community forums](https://community.postman.com/c/events/6) when you have the chance.

After the event, you can fill out a [contribution report](https://airtable.com/appgTEMsLIUf1NXUj/shrM6Uh7WqOEJJQZ7) and I'll be notified of it's completion :)
