### ISSUE TITLE
Contribution Proposal - Automating Hash Generation With Postman (Motunrayo Ilawole)

### ISSUE THREAD

**Issue by TunrayoIlawole** [postman-open-technologies/Postman-Supernova-Program#18]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking
- [ ] Event Hosting
- [x] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [ ] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Automating Hash Generation With Postman

### Contribution Date
09/09/2023

# Details
I would like to write an article that teaches how to use pre-request scripts in Postman to automate the generation of hashes to efficiently test secured API endpoints.
If approved, the plan is to publish on Dev.to by September 9th. I'll share on the community forums, tech communities I belong to and LinkedIn.

**Comment by Kcorb95** [comment]
Hi @TunrayoIlawole !

I think this is a great idea! Excited to see what you come up with :)

Please be sure to also share on the [community forums](https://community.postman.com/c/content-showcase/7) and on social media when you're ready!

**Comment by Kcorb95** [comment]
Hey @TunrayoIlawole ! 

Wanted to check in on how your post is going? Once this is complete, we'll be able to move forward with onboarding you officially as a Supernova :)

**Comment by TunrayoIlawole** [comment]
Hi @Kcorb95, i created the article and posted it on the community forums - https://community.postman.com/t/automating-hash-generation-with-postman/51573/1

**Comment by Kcorb95** [comment]
Thank you @TunrayoIlawole ! I'll be in touch shortly about next steps :)
