### ISSUE TITLE
Contribution Proposal - Demo the usage of Postman to High School Students (Shivan Bhatia)

### ISSUE THREAD

**Issue by ShivanBhatiaBA** [postman-open-technologies/Postman-Supernova-Program#19]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking

### For event types, will this event be in-person, virtual or hybrid?
- [ ] In-Person

### Contribution Name
Demo the usage of Postman to High School Students

### Contribution Date
Please enter formatted as 09/11/2023

### Link to Contribution (optional)
NA

### Projected Attendance (optional)
100

# Details
What are your plans for this contribution?
Next month, I am in the process of organizing an event in collaboration with the NGO to which I am affiliated. The objective of this event is to conduct a training session at a local high school, targeting approximately 100 participants. During this session, I will delve into the intricacies of Postman and API development using the Postman tool. The training will encompass a comprehensive understanding of its functionalities, applications, and the practical ways in which it can be employed.

The essence of this initiative is to equip these associates with a solid grasp of Postman's capabilities and its significance in the realm of API development. By imparting this knowledge, we aim to empower these participants with the tools and skills they need to harness the potential of Postman effectively. Through interactive sessions and hands-on demonstrations, attendees will gain insights into the practical aspects of utilizing Postman for various tasks, thus paving the way for a deeper understanding of API development.

In essence, this event serves as an opportunity to bridge the gap between theoretical knowledge and real-world application. By fostering an environment of learning and collaboration, we aspire to facilitate the growth of these associates, enabling them to make meaningful contributions in the field of API development using the versatile capabilities of Postman.

**Comment by Kcorb95** [comment]
Thanks @ShivanBhatiaBA !
This looks exciting! Please be sure to post on social media as you get closer to the event as well :)
