### ISSUE TITLE
Contribution Proposal - Live "Sou QA, vou começar a trabalhar com API e agora? (Cristina Nazário)

### ISSUE THREAD

**Issue by crisnazario** [postman-open-technologies/Postman-Supernova-Program#21]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking
- [ ] Event Hosting
- [ ] Article / Blog Post
- [x] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [x] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Sou QA, vou começar a trabalhar com API e agora?

### Contribution Date
09/14/2023

### Link to Contribution (optional)
Link to your contribution, if applicable

### Projected Attendance (optional)
Rough estimates are acceptable

# Details
I'm going to talk about how a QA should act when working with APIs for the first time on the team, which is important to know.
I will share my experiences, tips and use Postman to show examples.

Presentation duration: 1 hour
Website Link: https://programador.tv/

**Comment by Kcorb95** [comment]
Excellent work @crisnazario !

If you have a recording of the talk, please do share on the [community forums](https://community.postman.com/c/content-showcase/7) and on socials as well :)

**Comment by crisnazario** [comment]
The live was recorded on the platform.
Link: https://programador.tv/Watch?key=742e10ee-bd9b-484d-9c6b-08dbafd99b1b
