### ISSUE TITLE
Contribution Proposal - Explorando o Postbot (Cristina Nazário)

### ISSUE THREAD

**Issue by crisnazario** [postman-open-technologies/Postman-Supernova-Program#22]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking
- [ ] Event Hosting
- [ ] Article / Blog Post
- [x] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [x] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Explorando o Postbot

### Contribution Date
Please enter formatted as 09/21/2023

### Link to Contribution (optional)
Link to your contribution, if applicable

### Projected Attendance (optional)
Rough estimates are acceptable

# Details
What are your plans for this contribution?

I'll share about introducing Postbot to Postman, how it can help us during testing with REST APIs, and the benefits we can get from it.

Presentation duration: 1 hour
Website Link: https://programador.tv/

**Comment by Kcorb95** [comment]
Thanks for sharing @crisnazario ! Excited to see how it turns out :)

When you have a chance, please do share on the [community forums](https://community.postman.com/c/content-showcase/7) and on socials so we can re-share.

**Comment by crisnazario** [comment]
Hello @Kcorb95 ,
It was recorded, I shared it on the community forum and on Linkedin.

Linkedin: https://www.linkedin.com/feed/update/urn:li:activity:7110949562717995010/
Community: https://community.postman.com/t/explorando-o-postbot/52217
