### ISSUE TITLE
Contribution Proposal - API CONFERENCE 2023 (Sule-balogun Olanrewaju)

### ISSUE THREAD

**Issue by LarrySul** [postman-open-technologies/Postman-Supernova-Program#24]
# Contribution Proposal

## Contribution Type
- [ ] Event Speaking
- [x] Event Hosting
- [ ] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [ ] Virtual
- [x] In-Person
- [ ] Hybrid

### Contribution Name
Sule-balogun Olanrewaju

### Contribution Date
Please enter formatted as MM/DD/YYYY
18 Nov 2023

### Link to Contribution (optional)
Link to your contribution, if applicable

Event Website -- https://apiconf.net/
Call for proposal --- https://sessionize.com/api-conf-lagos-2023/

### Projected Attendance (optional)
Rough estimates are acceptable

300 - 500

# Details
What are your plans for this contribution?

The event is going to be the first of it's kind happening in Lagos, Nigeria and we have been putting preparation to ensure the event is a success ... We have made reservation for a venue and we still are looking for sponsors for the event . It's an event I'll be co-hosting with Gbadebo Bello who's an employee at Postman and other API professional. I'm looking at availing myself which will mean I'll be attend the conference physically from United Kingdom to Nigeria, and given a talk alongside other professionals. Quarterly, I'm also eligible for up to $500 which I also plan to use to support the event alongside swags and merch from Postman.

**Comment by Kcorb95** [comment]
This looks fantastic @LarrySul ! Please do share on our forums and on your socials as you get talks and other content setup :)

**Comment by Terieyenike** [comment]
Can I still register to attend or speak at APIConf @LarrySul?
