### ISSUE TITLE
Contribution Proposal - Postman Crash: Efficient Software Testing with Postman (Abubakar Sadiq Ismail and Funke Olasupo) ) 

### ISSUE THREAD

**Issue by ismaelsadeeq** [postman-open-technologies/Postman-Supernova-Program#5]
# Contribution Proposal

## Contribution Type
 - Event Speaking and Event Hosting

### For event types, will this event be in-person, virtual or hybrid?
-  Hybrid

### Contribution Name
Postman Crash: Efficient Software Testing with Postman

### Contribution Date
07/22/2023

# Details
## Event Details
- Event Organizer: Funke Olasupo and Abubakar Sadiq Ismail
- Speaker:  Abubakar Sadiq Ismail and Funke Olasupo 
- Date: July, 22nd, 2023
- Duration: 40 min
- Platform: Googlr Meet and physical

### 1. Introduction and Welcome
- I Abubakar Sadiq Ismail and Funke will introduce ourselves as the speakers and explain the event

### 2. Funke's Session: Getting Started with Postman
- Funke will cover the basics of Postman, including its key features, functionalities, and its role in API testing and development.
- Attendees will learn how to set up Postman, create requests, and manage collections.
- Duration: 15 minutes

### 3. Abubakar's Session: Efficient Software Testing with Functional Tests
- Abubakar will focus on efficient software testing using functional tests in Postman.
- Best practices and techniques for crafting effective functional tests will be shared
- Practical demonstrations will showcase the design of test scripts, handling different response types, and analyzing test results.
- Duration: 15 minutes

### 4. Q&A and Interactive Discussions
- Funke and Abubakar will facilitate a Q&A session to address audience questions and concerns.
- Interactive discussions will encourage knowledge-sharing and provide further insights into Postman and efficient software testing.
-  Duration: 10 minutes

## Expected Outcomes
- Gain a solid understanding of Postman and its role in software testing.
- Grasp the basics of setting up and utilizing Postman for API testing and development.
- Acquire practical knowledge and strategies for implementing efficient software testing through functional tests in Postman.
- Learn to automate and streamline testing processes using Postman.
- Gain confidence in conducting efficient software testing and enhancing application quality.

## Audience Benefits
- Comprehensive understanding of Postman and its capabilities.
- Step-by-step processes for setting up and utilizing Postman effectively.
- Valuable insights and best practices for crafting functional tests that ensure application robustness.
- Automation and streamlining of testing processes using Postman.
- Increased confidence in conducting efficient software testing and enhancing application quality.

**Comment by Kcorb95** [comment]
This looks great @ismaelsadeeq!
Do you have an expected attendance number? We'd love to send you some stickers if you'll have a bunch of people showing up in person :)

**Comment by ismaelsadeeq** [comment]
Yay, stickers will be cool, Physical attendance is optional though, but I will say 20 or less.

**Comment by ismaelsadeeq** [comment]
Sure, Kevin.
Many thanks

**Comment by ismaelsadeeq** [comment]
Sent, Event was a success 💯
