### ISSUE TITLE
Contribution Proposal - Nomoskar Kolkata (Sandip Palit)

### ISSUE THREAD

**Issue by SandipPalit** [postman-open-technologies/Postman-Supernova-Program#6]
## Contribution Type
- [x] Event Speaking
- [x] Event Hosting
- [ ] Article / Blog Post
- [ ] Video / Livestream
- [ ] Quickstarts / Translation Assistance

### For event types, will this event be in-person, virtual or hybrid?
- [x] Virtual
- [ ] In-Person
- [ ] Hybrid

### Contribution Name
Sandip Palit

### Contribution Date
5th August 2023, 05:00 PM IST (timezone: +05:30)

### Link to Contribution (optional)
https://lu.ma/pcknk

### Projected Attendance (optional)
NA

# Details
Are you looking to learn more about Postman and connect with like-minded professionals? Look no further than "Nomoskar Kolkata", the inaugural event of Postman Community Kolkata. This event aims to bring together industry leaders, professionals, and enthusiasts to foster an inclusive tech community. Join us to share knowledge and ask questions to our renowned speakers. Let's work together to build a stronger community.

Name: Nomoskar Kolkata
Date: 5th August 2023
Time: 5:00 - 7:00 PM IST

Agenda:
1. Intro to Postman Community Kolkata - Sandip Palit 
2. APIs 101 Using Postman - Aanchal Mishra 
3. Postman beyond testing - Abhinav Patel 
4. Set up your first Mock Server in Postman - Sayak Saha 

You can follow us on Linkedin : https://lnkd.in/dwMubXuW
and join our Discord server : https://lnkd.in/dh37XwJn

**Comment by Kcorb95** [comment]
This is exciting @SandipPalit!
When you have an idea for some of the speakers and talk abstracts, we'd love to do some marketing to boost registration for you.
Additionally, if you could share on the [community forums,](https://community.postman.com/c/events/6) that would be huge as well :)

Let me know how I can help!

**Comment by SandipPalit** [comment]
Hi @Kcorb95 , I have updated the details. Kindly let me know if I missed anything.

**Comment by Kcorb95** [comment]
Thanks @SandipPalit ! Scheduled some marketing for this. Good luck on your event! :)

**Comment by SandipPalit** [comment]
Hi @Kcorb95 , I submitted my Contribution last month, but it's not reflected in the [List of Current Contributions](https://github.com/postman-open-technologies/Postman-Supernova-Program/blob/main/pages/contributions/Current-Contributions.md). 

Should I submit it again?

**Comment by Kcorb95** [comment]
Hi @SandipPalit !

Looks like there's an error with our automation. I'll get that fixed and updated again shortly :)

Thanks for the heads up!
